name: 💡 Content Request
description: Have a content for the website? Please suggest! (Please submit a feature request for technical topics)
title: '[FEATURE]: '
type: Feature
labels:
  - enhancement

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of what feature you want to add or implemented.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Explain why you want this added. A clear and concise description of why you want this implemented.
    validations:
      required: true

  - type: textarea
    id: benefit
    attributes:
      label: Benefit
      description: Who will benefit from this feature?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please add screenshots if applicable
    validations:
      required: false

  - type: dropdown
    id: assignee
    attributes:
      label: Do you want to work on this request?
      multiple: false
      options:
        - 'Yes'
        - 'No'
    validations:
      required: false

  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else we should know about this content request?
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        You can also join our Discord community [here](https://discord.gg/PWm9NsFQzX)
