name: 🧱 General Inquiry
description: For general inquiries only. Use the bug report, feature request, or content request templates for those topics
title: "🧱 <Add your title here>"
lables: ["General Inquiry"]
body:
  - type: markdown
    attributes:
      value: "# General Inquiry"
  - type: textarea
    id: issuedescription
    attributes:
      label: What would you like to share?
      description: Provide a clear and concise explanation of your topic.
    validations:
      required: true
  - type: dropdown
    id: assignee
    attributes:
      label: Do you want to work on this topic?
      multiple: false
      options:
        - "Yes"
        - "No"
    validations:
      required: false
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else we should know about this topic?
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        You can also join our Discord community [here](https://discord.gg/mHtThpN8bT)
